"""
Email delivery — sends lecture notes via Gmail SMTP using only stdlib.

Tries port 587 (STARTTLS) first, falls back to port 465 (SSL) if the
connection is refused or times out.  Both attempts use a 10-second timeout
so the pipeline never hangs waiting for a blocked port.

Return value: (sent: bool, error_msg: str | None)
  - (True,  None)        → delivered
  - (False, None)        → credentials not configured; skipped
  - (False, "<reason>")  → delivery attempted but failed
"""
import logging
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)

SMTP_HOST    = "smtp.gmail.com"
SMTP_TIMEOUT = 10   # seconds per connection attempt


def _build_html_body(lecture_title: str, n_topics: int, n_actions: int) -> str:
    return f"""
<html><body style="font-family: Calibri, Arial, sans-serif; color: #1a1a2e; max-width: 640px; margin: auto;">
  <h2 style="color: #0f3e6f;">📚 Your Lecture Notes Are Ready</h2>
  <p>Your LectureAI notes for <strong>{lecture_title}</strong> have been generated.</p>
  <table style="border-collapse: collapse; width: 100%; margin: 16px 0;">
    <tr style="background:#0f3e6f; color:#fff;">
      <th style="padding:8px 12px; text-align:left;">Metric</th>
      <th style="padding:8px 12px; text-align:left;">Value</th>
    </tr>
    <tr style="background:#f4f7fb;">
      <td style="padding:8px 12px;">Topics covered</td>
      <td style="padding:8px 12px;"><strong>{n_topics}</strong></td>
    </tr>
    <tr>
      <td style="padding:8px 12px;">Action items</td>
      <td style="padding:8px 12px;"><strong>{n_actions}</strong></td>
    </tr>
    <tr style="background:#f4f7fb;">
      <td style="padding:8px 12px;">Languages</td>
      <td style="padding:8px 12px;">English + Mandarin (简体中文)</td>
    </tr>
  </table>
  <p>The attached <strong>lecture_notes.docx</strong> contains bilingual notes
  (English section followed by full Mandarin translation). Captions are
  included as <strong>captions.srt</strong>.</p>
  <p style="color:#555; font-size:0.9em;">Generated by LectureAI &mdash; automated lecture processing pipeline.</p>
</body></html>
"""


def _try_starttls(host: str, msg_bytes: bytes, sender: str, recipient: str,
                  password: str) -> None:
    """Connect on port 587 with STARTTLS. Raises on any failure."""
    with smtplib.SMTP(host, 587, timeout=SMTP_TIMEOUT) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(sender, password)
        server.sendmail(sender, recipient, msg_bytes)


def _try_ssl(host: str, msg_bytes: bytes, sender: str, recipient: str,
             password: str) -> None:
    """Connect on port 465 with implicit SSL. Raises on any failure."""
    with smtplib.SMTP_SSL(host, 465, timeout=SMTP_TIMEOUT) as server:
        server.ehlo()
        server.login(sender, password)
        server.sendmail(sender, recipient, msg_bytes)


def send_results_email(session_id: str) -> tuple[bool, str | None]:
    """
    Send lecture notes to the configured RECIPIENT_EMAIL.

    Returns (True, None) on success.
    Returns (False, None) if SMTP credentials are not configured (soft skip).
    Returns (False, error_msg) if delivery was attempted but failed.
    Never raises.
    """
    import json
    from app.config import get_settings

    settings = get_settings()

    if not settings.smtp_email or not settings.smtp_password:
        logger.info("[%s] SMTP credentials not configured — skipping email.", session_id)
        return False, None

    recipient   = settings.recipient_email or settings.smtp_email
    session_dir = settings.session_data_dir(session_id)
    outputs_dir = settings.session_outputs_dir(session_id)

    # Derive content for the email body
    lecture_title = "Lecture"
    n_topics = 0
    n_actions = 0
    summary_path = session_dir / "summary.json"
    if summary_path.exists():
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        lecture_title = summary.get("lecture_title", lecture_title)
        n_topics = len(summary.get("topics", []))
    ai_path = session_dir / "action_items.json"
    if ai_path.exists():
        n_actions = len(json.loads(ai_path.read_text(encoding="utf-8")))

    # Collect attachments that exist
    attachments: list[Path] = []
    for fname in ("lecture_notes.docx", "captions.srt", "captions.vtt"):
        p = outputs_dir / fname
        if p.exists():
            attachments.append(p)

    # Build message
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"Your Lecture Notes are Ready - {lecture_title}"
    msg["From"]    = settings.smtp_email
    msg["To"]      = recipient

    html_part = MIMEText(_build_html_body(lecture_title, n_topics, n_actions), "html", "utf-8")
    msg.attach(html_part)

    for path in attachments:
        with open(path, "rb") as fh:
            part = MIMEApplication(fh.read(), Name=path.name)
        part["Content-Disposition"] = f'attachment; filename="{path.name}"'
        msg.attach(part)

    msg_bytes = msg.as_bytes()
    last_exc: Exception | None = None

    # Try port 587 (STARTTLS), then port 465 (SSL)
    for attempt, label in [(lambda: _try_starttls(SMTP_HOST, msg_bytes,
                                                   settings.smtp_email, recipient,
                                                   settings.smtp_password), "587/STARTTLS"),
                           (lambda: _try_ssl(SMTP_HOST, msg_bytes,
                                             settings.smtp_email, recipient,
                                             settings.smtp_password), "465/SSL")]:
        try:
            logger.info("[%s] Trying SMTP %s → %s via %s…",
                        session_id, label, recipient, SMTP_HOST)
            attempt()
            logger.info("[%s] Email delivered to %s (%s, %d attachment(s)).",
                        session_id, recipient, label, len(attachments))
            return True, None
        except (TimeoutError, OSError, smtplib.SMTPConnectError,
                smtplib.SMTPServerDisconnected) as exc:
            logger.warning("[%s] SMTP %s failed: %s", session_id, label, exc)
            last_exc = exc
        except smtplib.SMTPAuthenticationError as exc:
            # Auth failure is definitive — no point trying the other port
            err = "SMTP authentication failed — check your app password"
            logger.error("[%s] %s: %s", session_id, err, exc)
            return False, err
        except smtplib.SMTPException as exc:
            logger.warning("[%s] SMTP %s error: %s", session_id, label, exc)
            last_exc = exc

    err_msg = ("SMTP connection failed on both port 587 and 465 "
               "(network may be blocking outbound mail) — download notes directly")
    logger.warning("[%s] All SMTP attempts failed. Last error: %s", session_id, last_exc)
    return False, err_msg
